spring:
  application:
    name: spring-data-jpa tutorial
  datasource:
    url: jdbc:mysql://localhost:3306/spring_jpa
    username: root
    password: root
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
open:
  api:
    description: Spring data jpa
    version: v1.0.0
    title: API document
    serverUrl: http://localhost:8080
    serverName: server